[package]
name = "db_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
names = "0.14.0"
rusqlite = "0.31.0"
thiserror = "1.0.61"
